version: '3.7'

services:
  go-app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./cmd/api:/go/src/go-app/cmd/api
    environment:
      - SCOPE=local
    ports:
      - "8080:8080"
